AllCops:
  TargetRubyVersion: 2.3

MethodLength:
  Max: 200

LineLength:
  Max: 175

AbcSize:
  Max: 175

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

# syntax is not common outside of the ruby community; try to reduce the opinionated back and forth as a more language neutral community
Style/SafeNavigation:
  Enabled: false
